### ISSUE TITLE
When running cloud-init in VirtualBox, disable "cloud" discovery

### ISSUE THREAD

**Issue by indiebox** [indiebox/ubos-admin#22]
cloud-init attempts to do things such as HTTP GET on the Amazon EC2 "well-known" URL to obtain configuration info. It shouldn't do that if it is known that this instance does not run there.

**Comment by indiebox** [comment]
This is how to do that: https://wiki.archlinux.org/index.php/Cloud-init#Configuring_data_sources

**Comment by indiebox** [comment]
Workaround for the time being. As root, execute:

    systemctl stop cloud-init
    systemctl disable cloud-init

**Comment by jimfenton** [comment]
```
systemctl disable cloud-init
```
doesn't seem to be doing anything. It doesn't give any messages indicating it did anything, and on reboot it tries to start cloud-init again.

**Comment by indiebox** [comment]
systemctl enable cloud-init

should print something about a symlink being created, and

    systemctl disable cloud-init

should print something about a symlink being removed. I just tried and it seems to work for me.

**Comment by jimfenton** [comment]
If I do those steps, it does print something about symlinks being created and removed. But if I reboot after disabling, I still get a bunch of warning messages from cloud-init.

**Comment by jimfenton** [comment]
Ah: I'm not at all sure what cloud-final is, but it seems to be invoking cloud-init. This:
```
systemctl disable cloud-final
```
seems to do the trick.

**Comment by indiebox** [comment]
Removed in incoming red.
